name: pre-commit
description: Execute pre-commit for Terraform codebase
inputs:
  terraform-version:
    description: Terraform version supported for use in evaluation
    required: true
  terraform-docs-version:
    description: Version of terraform-docs to use when evaluating checks
    required: false
    default: v0.16.0
  tflint-version:
    description: Version of tflint to use when evaluating checks
    required: false
    default: latest
  args:
    description: Arguments to pass to pre-commit
    required: false
    default: '--all-files --color always --show-diff-on-failure'
  install-hcledit:
    description: Install hcledit for pre-commit
    required: false
    default: 'false'
  hcledit-version:
    description: Version of hcledit to install when `install-hcledit` is true
    required: false
    default: 0.2.3

runs:
  using: composite
  steps:
    - name: Install Terraform v${{ inputs.terraform-version }}
      shell: bash
      run: |
        DIR="$HOME/$(date %+s)-${RANDOM}"
        tf_archive=terraform_${{ inputs.terraform-version }}_linux_amd64.zip
        mkdir -p "${DIR}/bin"
        curl -sSo $DIR/$tf_archive https://releases.hashicorp.com/terraform/${{ inputs.terraform-version }}/${tf_archive}
        unzip -qq "$DIR/${tf_archive}" terraform -d $DIR/bin
        rm $DIR/${tf_archive} 2> /dev/null
        echo "$DIR/bin" >> $GITHUB_PATH
        echo "DIR=$DIR" >> $GITHUB_ENV

    - name: Install pre-commit dependencies
      shell: bash
      run: |
        pip install -q pre-commit

        curl -sSLo $DIR/terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/${{ inputs.terraform-docs-version }}/terraform-docs-${{ inputs.terraform-docs-version }}-$(uname)-amd64.tar.gz
        tar -xzf $DIR/terraform-docs.tar.gz -C $DIR terraform-docs
        rm $DIR/terraform-docs.tar.gz 2> /dev/null

        if [[ "${{ inputs.tflint-version }}" == "latest" ]]; then
          curl -sSL "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > $DIR/tflint.zip
        else
          curl -sSLo $DIR/tflint.zip https://github.com/terraform-linters/tflint/releases/download/${{ inputs.tflint-version }}/tflint_linux_amd64.zip
        fi
        unzip -qq $DIR/tflint.zip tflint -d $DIR/bin
        rm $DIR/tflint.zip 2> /dev/null

        if [[ "${{ inputs.install-hcledit }}" == "true" ]]; then
          curl -sSLo $DIR/hcledit.tar.gz https://github.com/minamijoyo/hcledit/releases/download/v${{ inputs.hcledit-version }}/hcledit_${{ inputs.hcledit-version }}_$(uname)_amd64.tar.gz
          tar -xzf hcledit.tar.gz -C $DIR hcledit
          rm $DIR/hcledit.tar.gz 2> /dev/null
        fi

    - name: Execute pre-commit
      shell: bash
      run: pre-commit run ${{ inputs.args }}
