name: 'pre-commit-min'
description: 'Pre-commit check against minimum supported Terraform version'
inputs:
  version:
    description: 'Minimum version supported for use in evaluation'
    required: true
  directory:
    description: 'Directory to check with pre-commit using minimum version'
    required: true
  args:
    description: 'Additional arguments to pass to pre-commit'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Terraform v${{ inputs.version }}
      shell: bash
      run: |
        curl -sO https://releases.hashicorp.com/terraform/${{ inputs.version }}/terraform_${{ inputs.version }}_linux_amd64.zip
        unzip -qq terraform_${{ inputs.version }}_linux_amd64.zip && rm terraform_${{ inputs.version }}_linux_amd64.zip 2> /dev/null && sudo mv terraform /usr/bin/

    - name: Install pre-commit dependencies
      shell: bash
      run: pip install -q pre-commit

    - name: Execute pre-commit
      shell: bash
      run: |
        if [[ ${{ inputs.directory }} != '.' ]]; then
          pre-commit run terraform_validate --color always ${{ inputs.args }} --files ${{ inputs.directory }}/*
        else
          pre-commit run terraform_validate --color always ${{ inputs.args }} --files $(ls *.tf)
        fi
